spring.application.name=employee-management
spring.data.mongodb.uri=mongodb://localhost:27017/employee_management
server.port=8080

# IMPORTANT: replace this in production with a long secret from an environment variable.
app.jwt.secret=change-this-secret-change-this-secret-change-this-secret-123456
app.jwt.expiration-ms=86400000

springdoc.swagger-ui.path=/swagger-ui.html
